### ISSUE TITLE
Cannot open '/dev/video0': 13, Permission denied

### ISSUE THREAD

**Issue by mbpz** [nightkidxmd/libv4l2#1]
audit(0.0:31): avc: denied { getattr } for path="/dev/video0" dev="tmpfs" ino=15046 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:video_device:s0 tclass=chr_file permissive=1
E/V4L2: opendevice() Cannot open '/dev/video0': 13, Permission denied

**Comment by leaf918** [comment]
how to fix this issue?
